### ISSUE TITLE
Update to newer Elasticsearch images

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#102]
Should use Elasticsearch image `docker.elastic.co/elasticsearch/elasticsearch:5.6.2` (not the one from Docker Hub).

For configuration, we probably need to disable security.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

@jansule Can you do this? You have more experience setting up the Docker image provided by Elasticsearch.

- [ ] update `docker-compose-db.yml`
- [ ] developer test

**Comment by jansule** [comment]
@nuest yes I can do it. It's on my task list.

**Comment by nuest** [comment]
This is outdated by now, fixed in #109
