### ISSUE TITLE
candidate selection view 

### ISSUE THREAD

**Issue by TeKraft** [o2r-project/o2r-platform#107]
Clicking on "show options" button one gets a view with files that are candidates for substitution in two columns.

- Right column: base ERC-files
- Left column: overlay ERC-files

with the possibility to switch those files and substitute those ERCs

**Comment by MarkusKonk** [comment]
The other way around: Left column base erc, right column overlay

**Comment by TeKraft** [comment]
commit https://github.com/o2r-project/o2r-platform/commit/5be0d29d9b88795f8414ca644e08a969a510f9b8 closes this issue
