### ISSUE TITLE
Runnin the UI via https gives error for loading licenses

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#172]
When running the platform via an https web service, the license JSON cannot be loaded because of mixed content issues. This eventually means **no compendia can be created**.

```
angular.js:12836 Mixed Content: The page at 'https://o2r.uni-muenster.de/#!/creationProcess/yUkZW' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://licenses.opendefinition.org/licenses/groups/all.json'. This request has been blocked; the content must be served over HTTPS.
```

![image](https://user-images.githubusercontent.com/1325054/35240151-cfe8923c-ffb2-11e7-875a-8f2f47145b66.png)

The OKFN is in the process of changing their infrastructure, but I don't think we can wait for that, see https://github.com/okfn/licenses/issues/45 and https://github.com/okfn/opendefinition/issues/7

**Possible solutions:**

- run a proxy for the API
- save a local copy of the JSON file
- use an existing https proxy for http pages (not sure this is possible)

**Comment by MarkusKonk** [comment]
Currently, there is sth broken regarding the metadata. I don't get any "o2r" metadata, just "raw" metadata. This needs to be fixed first. Otherwise, I cannot test it. @7048730 Do you have an idea?
I tried it with the questiondriven ERC from the public share examples.

**Comment by 7048730** [comment]
I changed the name of the outputfiles to include a version number as discussed here:
https://github.com/o2r-project/o2r-meta/issues/80

Are you speaking of the very latest version of o2r-meta (`e0025d0b6a26ce33b6e21ab53aba89768a02efc3`)?

**Comment by MarkusKonk** [comment]
Not sure which version is used by the services as we do not use it directly but via the according service: We are using the following docker compose: https://github.com/o2r-project/o2r-platform/blob/master/docker-compose.yml

**Comment by nuest** [comment]
I'll have a fixed docker-compose file in 10 minutes.

**Comment by 7048730** [comment]
Concerning the the missing o2r metadata in the database: 

fix here to be able to parse a file named `^metadata_o2r_.*\.json$`
https://github.com/o2r-project/o2r-muncher/blob/776a9f5768bf8e32ac6f75e6a7dd39392f5f886e/config/config.js#L156

**Comment by MarkusKonk** [comment]
I created a local file including the licences.
