### ISSUE TITLE
Show ORCID ID next to author

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#18]
See

![orcid-id-user](https://cloud.githubusercontent.com/assets/1325054/18578203/e9d0c564-7bee-11e6-917e-7fa6b846268b.jpg)

**Comment by 7048730** [comment]
so wie 
```<a href="http://orcid.org/{{creator.orcid}}"><img class="inline-orcid" src="/static/img/orcid.png"``` /></a>
icon wie: https://zenodo.org/static/img/orcid.png

**Comment by nuest** [comment]
Genau so. 

Siehe auch

- https://members.orcid.org/logos-web-graphics
- http://orcid.org/trademark-and-id-display-guidelines

**Comment by 7048730** [comment]
[Recent orcid display guidelines](https://orcid.org/blog/2017/05/16/journal-display-guidelines)

**Comment by nuest** [comment]
After logging in, the ORCID iD is shown next to the user name:

![image](https://user-images.githubusercontent.com/1325054/30687501-b875e54e-9ebb-11e7-8c67-1f972255ac30.png)

- [ ] re-check if this is compliant with ORCID's guidelines

**Comment by 7048730** [comment]
They recommend it like this:


Authorname ![](https://orcid.org/sites/default/files/images/orcid_16x16(1).gif) orcid.org/0000-0001-2345-6789

**Comment by nuest** [comment]
So it is not compliant.

- [ ] fix for main page
- [ ] re-check and fix for compendium view page
