### ISSUE TITLE
Add option to unhide BagIt and metadata files

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#20]
For most users, the _BagIt-specific files_ and _metadata files_ are not relevant when they view the compendium in the browser. There should be a unobtrusive link to display them, but by default they should be either (a) hidden, or (b) shown in "grey" or somehow less prominent.

This could be done with a fixed whitelist in the UI, based on filenames/paths. If this "hiding" is limited to BagIt, we could even show the contents of the data folder by default, and only show the full folder tree when BagIt display is enabled.

The list of files would currently comprise

- `.erc` - everything within the directory `data/.erc` in a Bagit compendium
- `manifest-<alg>.txt`
- `bagit.txt`
- `tagmanifest-<alg>.txt`
- `bag-info.txt`
- `fetch.txt`

**Comment by nuest** [comment]
@7048730 Did I miss anything here?

**Comment by jansule** [comment]
@nuest this has not been implemented yet. I will do it in the near future.

**Comment by jansule** [comment]
@nuest a first simple implementation has been pushed (see here: ba1a6d479cc2913604d21f5f49e42f38cc1851cc). This solution assumes that the author's workspace will always be in a folder named `data`.

**Comment by nuest** [comment]
It's not only about hiding bagit files, but also o2r metadata and configuration stuff. I strongly recommend that we maintain a list (of regexes?) in the config file where we can configure multiple patterns to be hidden.

In the UI: does the user see the `/data` folder, or is only it's content shown?

**Comment by jansule** [comment]
> In the UI: does the user see the /data folder, or is only it's content shown?

Right now, only the folder's content is shown. But this is just a temporary solution. We were thinking about __highlighting the workspace__ instead of __hiding bagit files etc__. This might be more comfortable and less confusing for the user. 

>  I strongly recommend that we maintain a list (of regexes?) in the config file where we can configure multiple patterns to be hidden.

This seems to be a reasonable point.

**Comment by MarkusKonk** [comment]
I change some details, should be sufficient for now. Current state:
![bild1](https://cloud.githubusercontent.com/assets/2863409/24866309/078ad834-1e0a-11e7-8ad8-5fd2bb82bc0a.png)

![bild2](https://cloud.githubusercontent.com/assets/2863409/24866312/0aee49d4-1e0a-11e7-937a-bf7f399be762.png)
