### ISSUE TITLE
Downloads with and without container image

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#26]
When downloading a container, it should be possible not to include the image file, because that might be quite large. The API already supports this.

**Comment by jansule** [comment]
This has already been implemented in a previous commit.

**Comment by nuest** [comment]
The UI should show the download size before users click on the actual download button. This could be integrated in the small pop-up menu.

@jansule Could you easily calculate the overall size from the current API? Or would you need a sum to be included in the response from the server?

**Comment by jansule** [comment]
Good idea!

@nuest Generally, I can do it client side. In terms of performance it might be smarter to do it server side, so the overall size only needs to be calculated once. What do you think?

**Comment by nuest** [comment]
Well... a simple addition of n numbers, I'd rather put the load to the client's browser than on the server (and run into troubles when I persists that setting etc.). So I'd start with client-side until you recognize issues with the performance.
