### ISSUE TITLE
Show error messages at failed upload

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#27]
The server sends a concrete message if an upload fails, which should be displayed. E.g. if a user level does not allow upload, then it reponds with

```
401

{"error":"user level does not allow compendium creation"}
```

but the UI only tells the user "File upload failed!".

**Comment by jansule** [comment]
Done. 
See here: https://github.com/o2r-project/o2r-platform/commit/cf277b73fc3a379506d1580abbf361c964e2a56b
