### ISSUE TITLE
platform documentation does not refer to supported docker-compose versions + elasticsearch configuration

### ISSUE THREAD

**Issue by MatthiasHinz** [o2r-project/o2r-platform#28]
Hi,
I just tried to set up the o2r platform using docker-compose on Ubunto Xenial 16.04 LTS
It seems like my docker-compose installation is not supported, but the documentation is missing out information on the installation requirements.

This is what I did:
```
matthiashinz@xxx:~/o2r-platform$ docker-compose --version
docker-compose version 1.5.2, build unknown
matthiashinz@xxx:~/o2r-platform$ docker-compose --file test/docker-compose-db.yml up -d
ERROR: In file './test/docker-compose-db.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

**Comment by MatthiasHinz** [comment]
Furthermore, it seems like the elasticsearch container requires additional configuration that is not documented. The container does not start up with default settings.

[https://www.elastic.co/guide/en/elasticsearch/reference/5.0/_maximum_map_count_check.html](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/_maximum_map_count_check.html)

**Comment by nuest** [comment]
Anleitung zur Problemlösung für Elasticsearch hier: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docker.html#docker-cli-run-prod-mode
