### ISSUE TITLE
Swallowed error message when "Automatically start analysis" is checked during upload

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#33]
User does _not_ have the required user level for upload.

When I have checked the "Automatically start analysis" box at compendium upload, I get "File uploaded successfully 100%".

When I have _not_ checked the box, I see the correct error message "File upload failed! user level does not allow compendium creation"

**Comment by jansule** [comment]
This bug has already been recognized and will be fixed soon.
