### ISSUE TITLE
create strings in arrays to objects

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-platform#34]
AngularJS has problems binding to primitives. Therefore `arrays containing strings` should be changed to `objects` to work properly on client side. I suggest following schema: 
```
"key": [{"name": String}, {"name": String}]
```
Here an example for the `keywords`-attribute:

```json
"keywords": [{"name": "reproducible"}, {"name": "research"}]
```

**Comment by 7048730** [comment]
I already made a nasty remark on angular concerning the same question on the meta suite repo. I think we will have lists of json strings or other primitives anyway (at least when working this 3rd party schemas), so we better get a fix for this. Should be possible, list is a really simple object, broadly used
