### ISSUE TITLE
Add UI for submission via public share

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#36]
Add UI for the new submission feature via a public share URL. The user must paste a URL into a form field, that's all.

API documentation: http://o2r.info/o2r-web-api/public-share/

Example share URL can be found in the integration tests of loader: https://github.com/o2r-project/o2r-loader/blob/master/test/api.js

See also #35 - loader should work with the known docker-compose configurations.

**Comment by LukasLohoff** [comment]
The API documentation is not correct at the moment! Meanwhile you can find an updated version at https://github.com/LukasLohoff/o2r-web-api/blob/master/docs/public-share.md
