### ISSUE TITLE
Login feature

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#4]
After the authentication microservice is implemented, see https://github.com/o2r-project/o2r-bouncer, add a "Login with ORCID" button to the page. Add a "?" button or some kind of link to a page with details about

- the information we store
- ORCID using Google Analytics and how to opt out (and enable login on our site)
  - http://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/5534995-allow-login-to-orcid-org-without-google-analytics
  - http://support.orcid.org/knowledgebase/articles/159728

**Comment by jansule** [comment]
Information page has been added. See [here](https://github.com/o2r-project/o2r-platform/commit/be78e795fc1b32868b0a8110fed7925c3fd55207).
