### ISSUE TITLE
Add metadata to image build on Docker Hub

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#43]
At least version and build tag should be included, see https://github.com/o2r-project/o2r-muncher/tree/master/hooks (see comments in these files for documentation) and https://github.com/o2r-project/o2r-muncher/blob/master/Dockerfile

**Comment by nuest** [comment]
@jansule @MarkusKonk Where do you define the version of the app?

**Comment by nuest** [comment]
@jansule @MarkusKonk Where do you define the version of the app?

**Comment by MarkusKonk** [comment]
I updated the readme. Version number is at the end of the file.

**Comment by nuest** [comment]
Implemented in https://github.com/o2r-project/o2r-platform/commit/0e2c169d19924d3d355d21d1f695557d1560cf93

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/28928416-66b0e520-786d-11e7-839d-12e559aa6a33.png)

**Comment by nuest** [comment]
Metadata @ microbadger: https://microbadger.com/images/o2rproject/o2r-platform
