### ISSUE TITLE
Add cookie information page and popup

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#5]
With the OAuth2-based login we start using cookies (about [cookie law](https://www.cookielaw.org/faq/). Therefore we must add a cookie disclaimer to the user page.

I suggest to use https://silktide.com/tools/cookie-consent

@JanKoppe please clarify the current state of what cookies store. May be possible to reuse some phrases from other cookie info pages, e.g. https://soundcloud.com/pages/cookies

**Comment by JanKoppe** [comment]
Cookies only contain the field `connect.sid`, which includes a unique reference to a session (including auth details, if the user is authenticated via orcid) in our internal Database.

**Comment by nuest** [comment]
See also https://www.e-recht24.de/artikel/datenschutz/8451-hinweispflicht-fuer-cookies.html

**Comment by jansule** [comment]
I added a cookie popup ([see here](https://github.com/o2r-project/o2r-platform/commit/19c6c0f38a394d1f5ca4bc4a3fbfb763f90d2363)) Is it enough to link to the orcid cookie policy in the popup or do we have to create our own policy page?

**Comment by nuest** [comment]
Yes, let's include a link to our own privacy page, even if it doesn't contain much. 

That page should also have information about what we store in our database.

**Comment by jansule** [comment]
Privacy page has been created. [See here](https://github.com/o2r-project/o2r-platform/commit/be78e795fc1b32868b0a8110fed7925c3fd55207)
