### ISSUE TITLE
Add minimal shipment UI for Zenodo

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#60]
The ERC has four licenses for all of the components, but Zenodo only has one metadata for everything.

Therefore after clicking on "Ship to Zenodo", a modal should be shown where a user is told he has to choose _one_ license for the whole shipment. This should be a dropdown.

The use must also be shown the already selected licenses for the parts of a compendium.

This is of course different for other recipients.

**Comment by MarkusKonk** [comment]
will already be part of the creation process in the required metadata section
