### ISSUE TITLE
Simplify license selection

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#62]
[as discussed during the workshop last month]

The UI should offer a minimal and simple solution for licenses first, and only on user interaction provide the full UI with four drop-downs etc. So, the o2r platform should have "open" defaults so that the creator might not have to change anything.

Similar to http://choosealicense.com/ we can abstract from the details and be opinionated.

@7048730 @MarkusKonk (just going through my workshop notes:) Do you have anything to add?

**Comment by 7048730** [comment]
Conclusion from workshop discussion was: make it as easy as possible for authors, but we had one hint from a publisher that certain communities prefer certain ways of publishing, e. g. "only jupyter notebooks". So our default license should be open and integrative to (at the moment: ) R community publications.
Also note, that repositories mostly do not support different licenses for different parts of a publication, which forces us into another simplification.

**Comment by nuest** [comment]
The current state is quite nice:

![image](https://user-images.githubusercontent.com/1325054/30323960-858dd6e4-97bf-11e7-8a07-4a799251db01.png)

I would still add _several_ links to make clear that we are not giving legal advice, e.g. as a "Note" in a box with a short explanation. Links should be https://choosealicense.com/ and https://tldrlegal.com/ and http://opendefinition.org/licenses/

@MarkusKonk @7048730 should be point out here which license will be used if a repository only supports one license. Do we need a "main" license, or better a "fallback license"?
