### ISSUE TITLE
Update inspection user interaction

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#63]
This issue concerns two scenarios:

## 1. Inspecting remote ERC on the platform

The "Inspect" form should accept full Zenodo URLs as well as DOIs (as full links or resolved internally).

A user might manually enter these while reading a paper or copying a link from a document/website, which is not linked to an o2r platform instance.

## 2. Inspecting remote ERC coming from another platform

To inspect an ERC that is stored in a remote repository, we would like to be able to pre-fill the inspect form with a suitable value. This way, a button on a third party website can say "Inspect this ERC" and the user does not have to manually transfer an ID into the o2r platform start page.

URL examples, coming from third party sites could be

- `http://.../#/?inspect=10.124/sg22sdfsa` (DOI)
- `http://.../#/?inspect=https://zenodo.org/record/1`
- `http://.../#/?inspect=https://doi.org/10.124/sg22sdfsa`

## API updates

The server [currently only has an API](http://o2r.info/o2r-web-api/compendium/public_share/) for loading workspaces, not for inspection. See https://github.com/o2r-project/o2r-loader/issues/12

The server API must accept all allowed inputs, see above.

@LukasLohoff @jansule @MarkusKonk Comments/clarifications welcome!

**Comment by jansule** [comment]
This functionality has been added to the platform. If the inspect query exists, its content will be inserted into the input field of inspect.
**Note:** The URL looks like this: `http://.../#!/home?inspect=xyz`

We still have to agree on an API in the backend, as @nuest already mentioned.
