### ISSUE TITLE
Modals don't close when going backwards/forwards in history

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-platform#67]
When using the backwards and forwards button of a browser and a modal is opened, it will not close and overlap other contents. Therefore the modal.close() function should be called when controller will be destroyed

**Comment by MarkusKonk** [comment]
@jansule You are talking about the upload modal and the profile, right? In my case they close if I move backwards or forwards. So I close this issue. Feel free to re-open it if I am wrong.
