### ISSUE TITLE
Better intro/help for new visitors on landing page

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#72]
If a user opens our demo platform at https://o2r.uni-muenster.de/, she could be better guided what to do.

Here are my suggestions, feedback welcome!

- [x] highlight "you have to login first", maybe add a [popover](https://github.com/pleerock/ngx-popover) to the login button that is always visible
- [x] add a couple of links to example folders we already have on Sciebo so that a user can either copy and paste working public share URLs, or click on a link to put them in the form. May also be added as a popover or in a box underneath the two Create/Inspect boxes, with a short welcome text and some description of the respective examples.
- [x] add welcome text pointing to o2r.info
- [x] add a help pop-op to mentions of ERC directing to http://www.dlib.org/dlib/january17/nuest/01nuest.html
- ~~[ ] after registration, tell users they must send us an Email so that we can increase their rights on the platform!~~

**Comment by jansule** [comment]
This sounds like a good idea. Especially with respect to future study projects, etc.
Regarding the first point (highlighting login): Should we really do this? The platform is usable without logging in. Only if the user wants to use our special features (uploading, etc.) login is required. Adding this popup might give the impression that a login is needed. What do you think about this?

**Comment by nuest** [comment]
Good point. For now my opinion on this is: You guys figure something out and I'll be happy to complain if not all my suggestions are met or rightfully dismissed :-)

**Comment by MarkusKonk** [comment]
Regarding 3 and 4: Good idea and yes, should be part of the landing page.
1.) Login: That is a good point but strongly depends on the integration by the publisher/OJS and the submission process. Connected to that, the overall relevance of the landing page is questionable and maybe not required anymore. 
5.) relates to my question in #73, why not doing that automatically?
2.) I cannot imagine what exactly you mean :).

**Comment by nuest** [comment]
I agree that the landing page might disappear in the far future, but for now it's our only way to start a demo.

On 5.) I'm happy to do this, if we have some minimal monitoring.
On 2.) That was gibberish, rephrased it.

**Comment by nuest** [comment]
A further idea: Add the url to the web API endpoint in the footer, and a link to the API docs. Just a little bit of space but it shows that the service behind the platform is _open_!

```html
| <a href="http://o2r.info/o2r-web-api/" title="API specification">API</a> endpoint: <a href="https://o2r.uni-muenster.de/api/v1/"><code>https://o2r.uni-muenster.de/api/v1/</code></a>
```

should do it.

**Comment by jansule** [comment]
@nuest the links to the web api have been added to the footer. Issue will be closed, if all wanted components have been added.

**Comment by MarkusKonk** [comment]
@jansule The notification about the email that needs to be sent to admin is only in the profile section. There should also be a notification right after the first registration.

**Comment by MarkusKonk** [comment]
Regarding ref to our paper: I would prefer to place in the footer, too.

**Comment by MarkusKonk** [comment]
@nuest Is this still needed? Right now, everyone gets sufficient rights, right?

**Comment by nuest** [comment]
Right, the final point on the list is not needed anymore.
