### ISSUE TITLE
Admin backend

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#73]
An administrative backend where admin users (high enough levels) can easily change other users's levels would be useful. No more directly going to the database.

It should contain the user information (link to ORCID profile, full name from ORCID, current level), and a nice UI for using some pre-defined user levels, or alternatively entering a specific user level manually.

Reducing a user's level or making her admin should require a confirmation before saving.

API endpoint already exists, see http://o2r.info/o2r-web-api/user/#edit-user

_Should we integrate this in this app, or have an independent one?_

**Comment by jansule** [comment]
If this is only useful for the development, I would suggest to make an independent app.
If this should also be added as a general feature for the platform, it should be integrated.

**Comment by nuest** [comment]
No, it is not for development, quite the contrary: it is for _production_.

**Comment by MarkusKonk** [comment]
@nuest Shouldn't be too much effort. I will think about how, when, by whom, and let you know next week. 

But a few questions for now: How many user levels are there at moment? Why not just giving every registered the rights to submit/create ERCs automatically? What are the differences between users levels?

Regarding integration, it doesn't really matter if it is an independent or separate app as it shouldn't be visible for any other users than the admin. We can discuss the requirements next week.

**Comment by nuest** [comment]
We have multiple levels spread across several microservices... I'll make a list of the existing ones when we start implementing this. Roughly we have

- regular user/reader
- can execute ERC
- can upload/create ERC
- can change user levels 

Limitation: Because we wanted to have some control over who is uploading stuff, I guess. If we don't do that, we should have some minimal monitoring of what is going on on the platform, see https://github.com/o2r-project/o2r-bouncer/issues/4 & https://github.com/o2r-project/o2r-loader/issues/18

**Comment by nuest** [comment]
https://github.com/o2r-project/o2r-bouncer/issues/5 is now implemented in bouncer `> 0.6.0`. Let me know if it works for the admin backend!
