### ISSUE TITLE
Ship to Zenodo Button missing

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-platform#74]
Since the last redesign of the ercView, the `Ship to Zenodo`-Button is missing. It should be added again to the ercView.

**Comment by nuest** [comment]
If you want you could already make adjustments to ship to another recipient. @7048730 has almost completed shipping to b2share afair, so you could use a button-with-menu or so to be able to switch recipients.

It would also be really nice if this menu/button would show a small logo for each shipment destination.

**Comment by MarkusKonk** [comment]
That is quickly done. @7048730 lets me know as soon as he finished that.
