### ISSUE TITLE
User notification if upload via sciebo fails

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-platform#75]
If the upload via sciebo is successful, the user gets redirected to the entering of missing metadata. However, if the upload via sciebo fails, the user does not get any error message/information about what did go wrong, etc. Therefore, some popup, toast, etc. should be added to inform the user.

**Comment by MarkusKonk** [comment]
@jansule That is right. I included a toast message including the plain error message. Not user-friendly but enough for us.
