### ISSUE TITLE
Spatial attribute structure destroyed after medata input

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-platform#80]
When a shape is drawn within the creationProcess, the structure of `metadata.o2r.spatial` will be destroyed. It should still look like this:
```JSON
{
  "o2r": {
    "spatial": {
      "files": {},
      "union": {}
  }
}
```
Instead, it looks like this:

```JSON
{
  "o2r": {
    "spatial": {
      "files": {},
      "spatial": {
          "files": {},
          "union": {}
      }
    }
}
```

**Comment by jansule** [comment]
Seems to be a bug of `o2r-meta` since this happens directly after the upload.

**Comment by 7048730** [comment]
metadata dummy structure is a bit broken, after you guys committed into master branch. will take a while to clean up
