### ISSUE TITLE
Properly abort zip upload

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#82]
When uploading a large zip file (or a small one with a throttled connection, see Chrome developer tools (Network tab), and user clicks on cancel, the upload is still completed in the background.

Maybe this helps: https://github.com/danialfarid/ng-file-upload/wiki/Abort-Request

It seems like in the code here https://github.com/o2r-project/o2r-platform/blob/master/client/app/upload/uploadModal.controller.js#L19 only the dialog is cancelled, not the upload process. Maybe this one also helps: https://github.com/danialfarid/ng-file-upload/issues/1369

**Comment by jansule** [comment]
Following cases might occur when cancelling the upload process:

1. Cancelling during file upload
2. Cancelling after files have been uploaded and will now be processed in the backend (95% step)
