### ISSUE TITLE
Add link to compendium to creation view after first save 

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#89]
When the user creates a new ERC, the user can only click "Save" when all required metadata are entered. To encourage users to fill out more metadata, after saving the user stays in the creation form and is not taken to the compendium page.

- [ ] add a link / button "Go to compendium" above the right hand side menu (placement just a suggestion, I would make it a green button at the same location where the toaster was. Toaster appears, then disappears, button becomes visible. Magic.
- [ ] after first save, change the text of the "Save" button to "Update". Also say "updated succesfully" in the toaster.

**Comment by nuest** [comment]
Also the toaster is misplaced slightly to the right:
![image](https://user-images.githubusercontent.com/1325054/30324566-cf790574-97c1-11e7-9178-4c5d7fa08546.png)

**Comment by jansule** [comment]
@nuest Good idea! I would suggest to add a link to the ERC inside of the Toaster and keep it visible for a longer time.

@MarkusKonk To change the texts from "save" to "update" I would suggest to create a new view, that contains mainly the logic of creationProcess but is less restrictive (e.g. Cancelling would only cancel editing and not cancel the upload).

**Comment by MarkusKonk** [comment]
@jansule  The link should not be inside the toaster but in the same location where the toaster is and visible once it disappears.
 
First "save", then "update" is fine but cancel should remain as it is. Cancelling should not only cancel the editing process.

**Comment by jansule** [comment]
@MarkusKonk Keeping cancelling as it is would result in deleting the ERC, even though all required metadata is there. I would propose to make a soft cancel when updating metadata, where all edits will be reset to the state before the update-button has been clicked.
