### ISSUE TITLE
Add eslint configuration

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#9]
we could avoid the worst mistakes by using a eslint configuration for AngularJS, see https://www.npmjs.com/package/eslint-plugin-angular

**Comment by jansule** [comment]
This seems to be a good idea, since we are going to change our coding style according to [John Papas Best Practices](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md) anyway.

**Comment by jansule** [comment]
de2c862b21244d09c9d9efc51a73e0a210f0ba7b
