### ISSUE TITLE
Add support for main file and view file, relax requirements for development

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#95]
Currently, it is quite hard to test some workspaces and ERCs because "Main File" is a required field with a dropdown, where the dropdown is sometmes not files, so a developer can never save a compendium.

Anyways, to solve this, I see these steps

- [x] make "Main file" not required (during development)
- [x] add another field "Display file", in line with the current [draft of the specification](https://github.com/o2r-project/erc-spec/blob/post-workshop2017-update/docs/spec/index.md#main--display-file)
- [x] refactor code to not use "viewfile" anymore, as it may be confusing.

Coordinate with @7048730 about the state of the extractor and the (new?) property names for the  candidates for view file and display file.

**Just as an FYI**, I made the following changes to be able to run the "Pingtainer" again:

```diff
diff --git a/client/app/creationProcess/creationObject.factory.js b/client/app/creationProcess/creationObject.factory.js
index af5deb3..f37b9e5 100644
--- a/client/app/creationProcess/creationObject.factory.js
+++ b/client/app/creationProcess/creationObject.factory.js
@@ -59,6 +59,9 @@
         }

         function getRequired(){
+            let viewfiles_fix = erc.metadata.o2r.viewfiles;
+            viewfiles_fix.push(erc.metadata.o2r.paperSource);
+
             var required = {
                 title: erc.metadata.o2r.title,
                 description: erc.metadata.o2r.description,
@@ -66,7 +69,7 @@
                 softwarePaperCitation: erc.metadata.o2r.softwarePaperCitation,
                 license: erc.metadata.o2r.license,
                 author: erc.metadata.o2r.author,
-                viewfiles: erc.metadata.o2r.viewfiles,
+                viewfiles: viewfiles_fix,
                 viewfile: erc.metadata.o2r.viewfile
             };
             return angular.copy(required);
```

**Comment by 7048730** [comment]
just discussed and came up with this for the raw MD:
`mainfile`
`mainfile_candidates`
`viewfile`
`viewfile_candidates`
